language: ruby
rvm:
 - 2.2

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN
#   on:
#     branch: master
